server.servlet.session.tracking-modes: cookie

spring:
  application:
    name: dev-board

  datasource:
    url: ${DEV_BOARD_DB_URL}
    username: ${DEV_BOARD_DB_USERNAME}
    password: ${DEV_BOARD_DB_PASSWORD}

  jpa:
    open-in-view: false

    hibernate:
#      ddl-auto: none
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
